#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining2.prism" --constant_definitions="" --prop="" --num_episodes=1000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.01 --epsilon_dec=0.9999 --max_steps=100
python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining3.prism" --constant_definitions="" --prop="" --num_episodes=10000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=3 --neurons=256 --epsilon_min=0.01 --epsilon_dec=0.9999 --max_steps=100
#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining4.prism" --constant_definitions="" --prop="" --num_episodes=10000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.1 --epsilon_dec=0.9999 --max_steps=100
#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining5.prism" --constant_definitions="" --prop="" --num_episodes=70000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.1 --epsilon_dec=0.9999 --max_steps=100
#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining6.prism" --constant_definitions="" --prop="" --num_episodes=1000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.01 --epsilon_dec=0.9999 --max_steps=100
#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining7.prism" --constant_definitions="" --prop="" --num_episodes=1000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.01 --epsilon_dec=0.9999 --max_steps=100
#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining8.prism" --constant_definitions="" --prop="" --num_episodes=1000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.01 --epsilon_dec=0.9999 --max_steps=100
#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining9.prism" --constant_definitions="" --prop="" --num_episodes=1000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.01 --epsilon_dec=0.9999 --max_steps=100
#python cool_mc.py --task=safe_training --project_name="experiments" --rl_algorithm=cooperative_poagents --prism_file_path="dining10.prism" --constant_definitions="" --prop="" --num_episodes=25000  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.01 --epsilon_dec=0.9999 --max_steps=100

